security:
    oauth2:
        client:
            clientId: <secret>
            clientSecret: <secret>
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: profile
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false


spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  http:
    multipart:
      enabled: false
  datasource:
    #initialize: true
    url: jdbc:mysql://${spring.datasource.domain}/${spring.datasource.database}?${spring.datasource.params}
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    domain: localhost
    params: useLegacyDatetimeCode=false&serverTimezone=UTC
    database: simulacrum

management:
  endpoints:
    web:
      exposure:
        include: mappings
assets:
  directory: ./

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    alloy.simulacrum.api: INFO
#    org.springframework.web.socket.sockjs: DEBUG
