
export const TYPES = {
  PUT_CONTENT_ITEM_START: 'PUT_CONTENT_ITEM_START',
  PUT_CONTENT_ITEM_SUCCESS: 'PUT_CONTENT_ITEM_SUCCESS',
  PUT_CONTENT_ITEM_FAILURE: 'PUT_CONTENT_ITEM_FAILURE',
  LOAD_CONTENT_ITEMS_START: 'LOAD_CONTENT_ITEMS_START',
  LOAD_CONTENT_ITEMS_SUCCESS: 'LOAD_CONTENT_ITEMS_SUCCESS',
  LOAD_CONTENT_ITEMS_FAILURE: 'LOAD_CONTENT_ITEMS_FAILURE',
};
